// Deterministic scaffold generation: ScaffoldSpec -> file map. Feature toggles drive
// dependencies, env vars, module files, and the agent-context files. Zero-network — an
// optional LLM layer (NL-brief customization) lives elsewhere and is gated on a key.

import type { Features, ScaffoldResult, ScaffoldSpec, Template } from "./types.ts";

export function kebab(s: string): string {
  return s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "app";
}

function enabledFeatures(f: Features): string[] {
  return Object.entries(f).filter(([, on]) => on).map(([k]) => k);
}

function deps(spec: ScaffoldSpec): { deps: Record<string, string>; devDeps: Record<string, string> } {
  const d: Record<string, string> = {};
  const dev: Record<string, string> = { typescript: "^5.6.0", "@types/node": "^22.0.0" };
  if (spec.template === "ai-saas") {
    d.next = "^16.0.0";
    d.react = "^19.0.0";
    d["react-dom"] = "^19.0.0";
  }
  if (spec.features.auth) d["@clerk/nextjs"] = "^6.0.0";
  if (spec.features.billing) d.stripe = "^17.0.0";
  if (spec.features.rag) {
    d["drizzle-orm"] = "^0.36.0";
    d.postgres = "^3.4.0";
  }
  if (spec.features.mcp) {
    d["@modelcontextprotocol/sdk"] = "^1.0.0";
    d.zod = "^3.23.0";
  }
  return { deps: d, devDeps: dev };
}

function envVars(spec: ScaffoldSpec): string[] {
  const lines: string[] = [];
  if (spec.features.rag || spec.features.auth || spec.features.billing) lines.push("DATABASE_URL=postgres://localhost:5432/" + kebab(spec.name));
  if (spec.features.auth) lines.push("CLERK_SECRET_KEY=", "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=");
  if (spec.features.billing) lines.push("STRIPE_SECRET_KEY=", "STRIPE_WEBHOOK_SECRET=", "STRIPE_PRICE_ID=");
  if (spec.features.rag || spec.features.mcp) lines.push("ANTHROPIC_API_KEY=");
  return lines;
}

function renderPackageJson(spec: ScaffoldSpec): string {
  const { deps: d, devDeps } = deps(spec);
  const scripts: Record<string, string> =
    spec.template === "ai-saas"
      ? { dev: "next dev", build: "next build", start: "next start", lint: "eslint" }
      : { dev: "node --watch src/index.ts", start: "node src/index.ts" };
  if (spec.features.mcp) scripts["mcp"] = "node src/mcp/server.ts";
  return JSON.stringify(
    { name: kebab(spec.name), version: "0.1.0", private: true, type: "module", scripts, dependencies: d, devDependencies: devDeps },
    null,
    2,
  );
}

function renderTsconfig(): string {
  return JSON.stringify(
    { compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "bundler", strict: true, esModuleInterop: true, skipLibCheck: true } },
    null,
    2,
  );
}

function renderGitignore(): string {
  return ["node_modules/", "dist/", ".next/", ".env", ".env.local", "*.log", ".DS_Store"].join("\n") + "\n";
}

function renderEnvExample(spec: ScaffoldSpec): string {
  const lines = envVars(spec);
  return (lines.length ? lines.join("\n") : "# No secrets required for this configuration") + "\n";
}

function renderReadme(spec: ScaffoldSpec): string {
  const feats = enabledFeatures(spec.features);
  return [
    `# ${spec.name}`,
    "",
    spec.description ?? `A ${spec.template} project scaffolded by Project Bootstrapper.`,
    "",
    `**Template:** ${spec.template}  ·  **Features:** ${feats.length ? feats.join(", ") : "none"}`,
    "",
    "## Getting started",
    "```bash",
    "npm install",
    spec.template === "ai-saas" ? "npm run dev" : "npm run start",
    "```",
    "",
    "Copy `.env.example` to `.env` and fill in values. This repo is AI-agent-ready: see `CLAUDE.md` / `AGENTS.md`.",
    "",
    "_Generated by Project Bootstrapper._",
  ].join("\n");
}

function renderClaudeMd(spec: ScaffoldSpec): string {
  const feats = enabledFeatures(spec.features);
  const lines = [
    `# CLAUDE.md — ${spec.name}`,
    "",
    "Guidance for AI coding agents in this repo (generated by Project Bootstrapper).",
    "",
    `## Stack`,
    `- Template: **${spec.template}** (${spec.template === "ai-saas" ? "Next.js + TypeScript" : "Node + TypeScript"})`,
    feats.length ? `- Features: ${feats.join(", ")}` : "- Features: none",
    "",
    "## Conventions",
    "- TypeScript strict; small modules; no secrets in code (read from env).",
    spec.features.billing ? "- All money as integer cents; Stripe webhooks verify signatures." : "",
    spec.features.rag ? "- Ground answers in retrieved context; cite sources; never invent APIs." : "",
    spec.features.auth ? "- Every request is auth-scoped; never leak across users/tenants." : "",
    "",
    "## Layout",
    "- `src/` — application code" + (spec.features.mcp ? "; `src/mcp/server.ts` — MCP server" : ""),
    spec.features.docker ? "- `Dockerfile`, `docker-compose.yml` — local infra" : "",
    spec.features.ci ? "- `.github/workflows/ci.yml` — CI" : "",
  ].filter(Boolean);
  return lines.join("\n");
}

function renderAgentsMd(spec: ScaffoldSpec): string {
  return [
    `# AGENTS.md — ${spec.name}`,
    "",
    "Standard agent-instructions file (works with Cursor, Claude Code, OpenAI/Codex, etc.).",
    "",
    "- Follow the conventions in `CLAUDE.md`.",
    "- Run `npm install` then the dev script before assuming anything is broken.",
    "- Keep changes typed and small; don't commit secrets.",
  ].join("\n");
}

function renderMcpJson(spec: ScaffoldSpec): string {
  return JSON.stringify(
    { mcpServers: { [kebab(spec.name)]: { command: "node", args: ["src/mcp/server.ts"] } } },
    null,
    2,
  );
}

function renderMcpServer(spec: ScaffoldSpec): string {
  return [
    `// MCP server for ${spec.name}. Add your tools here.`,
    `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";`,
    `import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";`,
    `import { z } from "zod";`,
    "",
    `const server = new McpServer({ name: ${JSON.stringify(kebab(spec.name))}, version: "0.1.0" });`,
    "",
    `server.tool("ping", "Health check.", {}, async () => ({ content: [{ type: "text", text: "pong" }] }));`,
    "",
    `await server.connect(new StdioServerTransport());`,
  ].join("\n");
}

function renderEntry(spec: ScaffoldSpec): string {
  if (spec.template === "ai-saas") {
    return [`export default function Page() {`, `  return <main><h1>${spec.name}</h1></main>;`, `}`].join("\n");
  }
  return [`// ${spec.name} entry point`, `console.log("${spec.name} running");`].join("\n");
}

function renderAuth(): string {
  return [
    "// Auth scaffold (Clerk). Wire middleware + protect routes.",
    'export function requireAuth() { /* TODO: verify session, return user */ }',
  ].join("\n");
}

function renderBilling(): string {
  return [
    "// Billing scaffold (Stripe). Checkout + webhook.",
    'import Stripe from "stripe";',
    "export const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;",
    "// TODO: createCheckoutSession(); verify webhook signatures with STRIPE_WEBHOOK_SECRET.",
  ].join("\n");
}

function renderRag(): string {
  return [
    "// RAG scaffold (Postgres + pgvector). Ingest -> embed -> retrieve.",
    "// TODO: define a pgvector table; embed with your provider; cosine search.",
    "export async function retrieve(_query: string) { return []; }",
  ].join("\n");
}

function renderDockerfile(spec: ScaffoldSpec): string {
  return [
    "FROM node:22-slim",
    "WORKDIR /app",
    "COPY package*.json ./",
    "RUN npm install",
    "COPY . .",
    spec.template === "ai-saas" ? "RUN npm run build" : "",
    `CMD [${spec.template === "ai-saas" ? '"npm","start"' : '"node","src/index.ts"'}]`,
  ]
    .filter(Boolean)
    .join("\n");
}

function renderCompose(spec: ScaffoldSpec): string {
  const services: string[] = ["  app:", "    build: .", "    ports:", '      - "3000:3000"', "    env_file: .env"];
  if (spec.features.rag || spec.features.auth || spec.features.billing) {
    services.push(
      "  db:",
      "    image: pgvector/pgvector:pg16",
      "    environment:",
      "      POSTGRES_PASSWORD: postgres",
      "    ports:",
      '      - "5432:5432"',
    );
  }
  return ["services:", ...services].join("\n");
}

function renderCi(spec: ScaffoldSpec): string {
  return [
    "name: CI",
    "on: [push, pull_request]",
    "jobs:",
    "  build:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-node@v4",
    "        with: { node-version: 22 }",
    "      - run: npm install",
    spec.template === "ai-saas" ? "      - run: npm run build" : "      - run: node --check src/index.ts",
  ].join("\n");
}

export function buildScaffold(spec: ScaffoldSpec): ScaffoldResult {
  const name = kebab(spec.name);
  const f = spec.features;
  const files: Record<string, string> = {
    "package.json": renderPackageJson(spec),
    "tsconfig.json": renderTsconfig(),
    ".gitignore": renderGitignore(),
    ".env.example": renderEnvExample(spec),
    "README.md": renderReadme(spec),
    "CLAUDE.md": renderClaudeMd(spec),
    "AGENTS.md": renderAgentsMd(spec),
  };

  files[spec.template === "ai-saas" ? "src/app/page.tsx" : "src/index.ts"] = renderEntry(spec);
  if (f.auth) files["src/auth/index.ts"] = renderAuth();
  if (f.billing) files["src/billing/stripe.ts"] = renderBilling();
  if (f.rag) files["src/rag/index.ts"] = renderRag();
  if (f.mcp) {
    files["mcp.json"] = renderMcpJson(spec);
    files["src/mcp/server.ts"] = renderMcpServer(spec);
  }
  if (f.docker) {
    files["Dockerfile"] = renderDockerfile(spec);
    files["docker-compose.yml"] = renderCompose(spec);
  }
  if (f.ci) files[".github/workflows/ci.yml"] = renderCi(spec);

  return { name, template: spec.template, files, fileCount: Object.keys(files).length, features: enabledFeatures(f) };
}
